
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.maritza.pe.cpresentacion;

import com.maritza.pe.cmodelo.TipoDocumento;
import com.maritza.pe.cnegocio.TipoDocumentoBo;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.SQLException;



/**
 *
 * @author Alumno-PB203
 */
public class JPtipoDocumento extends javax.swing.JPanel {

    /**
     * Creates new form JPtipoDocumento
     */
    public JPtipoDocumento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablatipodocumento = new javax.swing.JTable();
        btneliminar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textfecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textnombre = new javax.swing.JTextField();
        textsigla = new javax.swing.JTextField();
        textnacionalidad = new javax.swing.JTextField();
        textestado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btnguardar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1400, 663));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("CRUD TIPO DOCUMENTO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        tablatipodocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablatipodocumento);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 530, 480));

        btneliminar.setBackground(new java.awt.Color(255, 102, 102));
        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 610, 90, 40));

        btnmodificar.setBackground(new java.awt.Color(255, 102, 102));
        btnmodificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(255, 255, 255));
        btnmodificar.setText("Modificar");
        add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 610, 100, 40));

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 610, 90, 40));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Siglas");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        textfecha.setBackground(new java.awt.Color(255, 204, 204));
        textfecha.setBorder(null);
        textfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfechaActionPerformed(evt);
            }
        });
        add(textfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 330, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nacionalidad");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Estado");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Fecha");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        textnombre.setBackground(new java.awt.Color(255, 204, 204));
        textnombre.setBorder(null);
        textnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnombreActionPerformed(evt);
            }
        });
        add(textnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 330, 30));

        textsigla.setBackground(new java.awt.Color(255, 204, 204));
        textsigla.setBorder(null);
        textsigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textsiglaActionPerformed(evt);
            }
        });
        add(textsigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 330, 30));

        textnacionalidad.setBackground(new java.awt.Color(255, 204, 204));
        textnacionalidad.setBorder(null);
        textnacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnacionalidadActionPerformed(evt);
            }
        });
        add(textnacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 330, 30));

        textestado.setBackground(new java.awt.Color(255, 204, 204));
        textestado.setBorder(null);
        textestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textestadoActionPerformed(evt);
            }
        });
        add(textestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 330, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 330, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, 330, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 330, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 330, 10));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 330, 10));

        btnguardar.setBackground(new java.awt.Color(255, 102, 102));
        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setText("Guardar");
        btnguardar.setBorder(null);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 80, 40));

        btnlimpiar.setBackground(new java.awt.Color(255, 102, 102));
        btnlimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnlimpiar.setText("Limpiar");
        btnlimpiar.setBorder(null);
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, 80, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/maritza/pe/cpresentacion/icons8-formulario-64.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 70, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void textfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfechaActionPerformed

    private void textnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnombreActionPerformed

    private void textsiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textsiglaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textsiglaActionPerformed

    private void textnacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnacionalidadActionPerformed

    private void textestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textestadoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed


//mi forma 
       try {
        TipoDocumentoBo tdbo = new TipoDocumentoBo();

        TipoDocumento td = new TipoDocumento();

        td.setNombre(textnombre.getText());
        td.setSiglas(textsigla.getText());
        td.setNacionalidad(textnacionalidad.getText());
        td.setEstado(textestado.getText());
        td.setFecha(textfecha.getText());


        String mensaje = tdbo.agregarTipoDocumento(td);

        JOptionPane.showMessageDialog(this, mensaje);

        textnombre.setText("");
        textsigla.setText("");
        textnacionalidad.setText("");
        textestado.setText("");
        textfecha.setText("");

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, "Error con la fecha: " + e.getMessage());
    }  

     }//GEN-LAST:event_btnguardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
    textnombre.setText("");
    textsigla.setText("");
    textnacionalidad.setText("");
    textestado.setText("");
    textfecha.setText("");    }//GEN-LAST:event_btnlimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable tablatipodocumento;
    private javax.swing.JTextField textestado;
    private javax.swing.JTextField textfecha;
    private javax.swing.JTextField textnacionalidad;
    private javax.swing.JTextField textnombre;
    private javax.swing.JTextField textsigla;
    // End of variables declaration//GEN-END:variables
}
